### PR TITLE
Add Notification Service

### PR DESCRIPTION
**Pull request by leeminkyu16**
Idk if it works, but backend will figure it out I'm sure lol

### CODE REVIEW

**Review by henryhu1 — APPROVED** [review]
naisu

**Review by abhaykshar — APPROVED** [review]
nice

**Review by andr-dev — APPROVED** [review]
Looks good!

One question though: for the subletr_pink, were we not already using a variable for this value? If not, are we planning on changing all our color choices to the palette?

**Comment by leeminkyu16** [comment]
The new `subletr_pink` is only for the temporary notification icon, not for use in any of the core application code.

**Pull request merged**
