### PR TITLE
Add indicator dots for multiple images

### PR DESCRIPTION
**Pull request by henryhu1**
250643914-1b55a0e4-3fe8-42a0-9911-be0ba7904f63

### CODE REVIEW

**Review by abhaykshar — COMMENTED** [review]
I think there needs to be a bit more spacing between the dots and the images, something like I added below with s or xs spacing size 
```kotlin
verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.xs))
```

**Comment by henryhu1** [comment]
> I think there needs to be a bit more spacing between the dots and the images, something like I added below with s or xs spacing size
> 
> ```kotlin
> verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.xs))
> ```

true, I added spacing so now it looks like

image

**Review by abhaykshar — APPROVED** [review]
Lgtm!

**Review by andr-dev — APPROVED** [review]
Nice!

**Review by leeminkyu16 — APPROVED** [review]
Let's Gamble, Try Merging

**Pull request merged**
