### PR TITLE
Add Google Maps SDK and map composable to listing details

### PR DESCRIPTION
**Pull request by henryhu1**

### CODE REVIEW

**Review by andr-dev — COMMENTED** [review]
Hmm, shouldn't the Google Maps API key only live on the backend?

**Comment by henryhu1** [comment]
> Hmm, shouldn't the Google Maps API key only live on the backend?

If there's a way to provide `build.gradle` the key from the backend that would be preferred yeah
[this maps composable I'm using is specifically for android](https://developers.google.com/maps/documentation/android-sdk/maps-compose) (might not be relevant), and right now I just have the actual key in `local.properties`.
Do you know how the backend can expose the key to the frontend?

**Comment by leeminkyu16** [comment]
Hmmmmm, yeah, I don't know if that's possible...
As far as I know, the `build.gradle` is purely used in compile-time. ;-;
I think the best we can do is obfuscate the API key?

**Review by leeminkyu16 — APPROVED** [review]
Let's Gamble, Try Merging

**Review by abhaykshar — APPROVED** [review]
maps!

**Pull request merged**
