### PR TITLE
create account field verifying

### PR DESCRIPTION
**Pull request by henryhu1**
checking the fields when creating a new account

### CODE REVIEW

**Review by andr-dev — APPROVED** [review]
Looks good, I'd wait for Min-Kyu to take a look as well to confirm I didn't miss anything

**Review by leeminkyu16 — COMMENTED** [review]
Can you change this to remove the supporting text if someone fixes the issue and presses "create account" or just fixes the issue on change?

Like, it's just a bit weird that it says "First name cannot be blank" after I filled the first name and tried creating an account again.
image

**Comment by henryhu1** [comment]
> Can you change this to remove the supporting text if someone fixes the issue and presses "create account" or just fixes the issue on change?

Yeah I definitely overlooked this

**Review by leeminkyu16 — APPROVED** [review]
Not the prettiest code but you gotta do what you gotta do.
Let's Gamble, Try Merging.

**Pull request merged**
