### PR TITLE
Add swagger UI + server static serve

### PR DESCRIPTION
**Pull request by andr-dev**

### CODE REVIEW

**Comment by leeminkyu16** [comment]
How do I test this UwU?

**Comment by andr-dev** [comment]
> How do I test this UwU?

Just run the server, `cargo build` in the server directory or you can run `./scripts/server_run`.
Navigate to localhost:3030 and it'll be served as index.html :)

**Review by leeminkyu16 — APPROVED** [review]
Sorry for the delay ;-;
Let's Gamble, Try Merging

I guess I should add a comment about this, but I don't think this works on Windows?
It gives a `error: linking with 'link.exe' failed: exit code: 1181` and `LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'`

**Comment by andr-dev** [comment]
> 

Wor

> Sorry for the delay ;-; Let's Gamble, Try Merging
> 
> I guess I should add a comment about this, but I don't think this works on Windows? It gives a `error: linking with 'link.exe' failed: exit code: 1181` and `LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'`

That error means that you are missing the sqlite3 library on your machine. I've tested on a windows machine with the sqlite3 dev library installed and it links properly.

**Pull request closed without merging**
